[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "csparse"
version = "0.1.0"
description = "A Python wrapper for the CSparse++ library"
authors = [{ name = "Bernie Roesler", email = "bernard.roesler@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.8"  # TODO setup CI to test on multiple versions

[tool.setuptools]
packages = ["csparse"]
